---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

Throughout this quarter, I've become better at making reader and viewer-centric plots and tables. Ultimately, data science is about digesting data and processing it to be consumable for people who never have to touch the raw data itself. It becomes an important skill to understand the audience and make visuals that are intuitive using that understanding. When I first started the course, my visualizations from lab 1 and 2 were lackluster because the annotations I presented did not add to the digestibility of the data and they did not bring forward data contexts to the viewer. Later, in lab 7, I struggled to make a visual that could encapsulate the three variables. I settled on a heat map, but I did not account the lack of numbers on the graph itself which made interpreting the exact data impossible. However, after making the necessary revisions, I feel that my lab 7 visualization is one of my strongest, using a clear bar chart and distinct colors. As a result of the trial and error I endured, I feel more confident in my ability to make better visualizations for a bigger audience using the tools I discovered in this class.
